-- ============================================================================
--  DIVASYA migration 008 — Shloka bank (bilingual)
--  44 well attested verses from the Gita, Upanishads, stotras and subhashitas,
--  each with an English and a Hindi meaning. The daily Sandesh rotates through
--  these, so it stays fresh for six weeks before repeating. Idempotent upserts.
-- ============================================================================

insert into public.shlokas (id,deva,translit,meaning,meaning_hi,source,deity) values
(1,'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।','Karmanye vadhikaraste, ma phaleshu kadachana',
 'You have the right to action alone, never to its fruits.',
 'तुम्हारा अधिकार केवल कर्म करने में है, उसके फल में कभी नहीं।','Bhagavad Gita 2.47','krishna'),
(2,'योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय।','Yogasthah kuru karmani sangam tyaktva dhananjaya',
 'Established in yoga, perform your work, letting go of attachment.',
 'हे धनंजय, आसक्ति त्यागकर, योग में स्थित होकर अपने कर्म करो।','Bhagavad Gita 2.48','krishna'),
(3,'श्रद्धावान् लभते ज्ञानं तत्परः संयतेन्द्रियः।','Shraddhavan labhate jnanam tatparah samyatendriyah',
 'The one with faith, devotion and mastered senses attains wisdom.',
 'श्रद्धावान, तत्पर और जितेन्द्रिय व्यक्ति ज्ञान प्राप्त करता है।','Bhagavad Gita 4.39','krishna'),
(4,'उद्धरेदात्मनात्मानं नात्मानमवसादयेत्।','Uddhared atmanatmanam natmanam avasadayet',
 'Lift yourself by your own self; never let the self sink.',
 'अपने आप से अपना उद्धार करो; अपने आप को गिरने मत दो।','Bhagavad Gita 6.5','krishna'),
(5,'तमसो मा ज्योतिर्गमय।','Tamaso ma jyotir gamaya',
 'Lead me from darkness to light.',
 'मुझे अंधकार से प्रकाश की ओर ले चलो।','Brihadaranyaka Upanishad','shiva'),
(6,'सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः।','Sarve bhavantu sukhinah sarve santu niramayah',
 'May all be happy; may all be free of illness.',
 'सभी सुखी हों; सभी नीरोग हों।','Shanti Mantra','durga'),
(7,'यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः।','Yatra yogeshvarah krishno yatra partho dhanurdharah',
 'Where Krishna and the archer Arjuna stand together, there victory is certain.',
 'जहाँ योगेश्वर कृष्ण और धनुर्धर अर्जुन हैं, वहीं विजय निश्चित है।','Bhagavad Gita 18.78','krishna'),
(8,'अहिंसा परमो धर्मः।','Ahimsa paramo dharmah',
 'Non violence is the highest dharma.',
 'अहिंसा ही परम धर्म है।','Mahabharata','hanuman'),
(9,'मन एव मनुष्याणां कारणं बन्धमोक्षयोः।','Mana eva manushyanam karanam bandha-mokshayoh',
 'The mind alone is the cause of both bondage and liberation.',
 'मनुष्य के बंधन और मोक्ष का कारण केवल मन ही है।','Amritabindu Upanishad','shiva'),
(10,'विद्या ददाति विनयं विनयाद् याति पात्रताम्।','Vidya dadati vinayam, vinayad yati patratam',
 'Knowledge gives humility; from humility comes worthiness.',
 'विद्या विनय देती है; विनय से पात्रता आती है।','Hitopadesha','ganesha'),
(11,'सन्तोषः परमं सुखम्।','Santoshah paramam sukham',
 'Contentment is the highest happiness.',
 'संतोष ही परम सुख है।','Subhashita','lakshmi'),
(12,'धैर्यं यस्य पिता क्षमा च जननी शान्तिश्चिरं गेहिनी।','Dhairyam yasya pita kshama cha janani',
 'Patience is his father, forgiveness his mother, and peace his lifelong companion.',
 'धैर्य जिसका पिता है, क्षमा माता, और शांति चिरकाल की संगिनी।','Subhashita','hanuman'),
(13,'आरोग्यं परमं भाग्यं स्वास्थ्यं सर्वार्थसाधनम्।','Arogyam paramam bhagyam',
 'Health is the highest fortune; wellbeing accomplishes all aims.',
 'आरोग्य परम भाग्य है; स्वास्थ्य समस्त प्रयोजनों का साधन है।','Subhashita','durga'),
(14,'ॐ सर्वेशां स्वस्तिर्भवतु।','Om sarvesham svastir bhavatu',
 'May there be wellbeing for all.',
 'सभी का कल्याण हो।','Shanti Mantra','shiva'),
(15,'न हि ज्ञानेन सदृशं पवित्रमिह विद्यते।','Na hi jnanena sadrisham pavitram iha vidyate',
 'Nothing in this world purifies like knowledge.',
 'इस संसार में ज्ञान के समान पवित्र कुछ भी नहीं है।','Bhagavad Gita 4.38','ganesha'),
(16,'यदा यदा हि धर्मस्य ग्लानिर्भवति भारत।','Yada yada hi dharmasya glanir bhavati bharata',
 'Whenever dharma declines, O Bharata, I manifest myself.',
 'हे भारत, जब-जब धर्म की हानि होती है, तब-तब मैं प्रकट होता हूँ।','Bhagavad Gita 4.7','krishna'),
(17,'परित्राणाय साधूनां विनाशाय च दुष्कृताम्।','Paritranaya sadhunam vinashaya cha dushkritam',
 'To protect the good and to end wrongdoing, I come age after age.',
 'सज्जनों की रक्षा और दुष्टों के विनाश के लिए मैं युग-युग में आता हूँ।','Bhagavad Gita 4.8','krishna'),
(18,'न जायते म्रियते वा कदाचित्।','Na jayate mriyate va kadachit',
 'The soul is never born and never dies.',
 'आत्मा न कभी जन्म लेती है और न कभी मरती है।','Bhagavad Gita 2.20','krishna'),
(19,'नैनं छिन्दन्ति शस्त्राणि नैनं दहति पावकः।','Nainam chindanti shastrani nainam dahati pavakah',
 'Weapons cannot cut the soul, nor can fire burn it.',
 'इस आत्मा को न शस्त्र काट सकते हैं, न अग्नि जला सकती है।','Bhagavad Gita 2.23','shiva'),
(20,'योगक्षेमं वहाम्यहम्।','Yoga-kshemam vahamyaham',
 'To those ever devoted, I carry what they lack and protect what they have.',
 'जो निरंतर मुझमें लगे हैं, उनका योगक्षेम मैं वहन करता हूँ।','Bhagavad Gita 9.22','krishna'),
(21,'सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज।','Sarva dharman parityajya mam ekam sharanam vraja',
 'Abandon all anxieties and take refuge in me alone; I will free you.',
 'समस्त धर्मों को छोड़कर केवल मेरी शरण में आ; मैं तुझे मुक्त कर दूँगा।','Bhagavad Gita 18.66','krishna'),
(22,'यद्यदाचरति श्रेष्ठस्तत्तदेवेतरो जनः।','Yad yad acharati shreshthas tat tad evetaro janah',
 'Whatever a great person does, others follow.',
 'श्रेष्ठ पुरुष जो-जो आचरण करता है, अन्य लोग उसी का अनुसरण करते हैं।','Bhagavad Gita 3.21','ganesha'),
(23,'आत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः।','Atmaiva hy atmano bandhur atmaiva ripur atmanah',
 'The self is its own friend, and its own enemy.',
 'मनुष्य स्वयं ही अपना मित्र है और स्वयं ही अपना शत्रु।','Bhagavad Gita 6.5','shiva'),
(24,'ईशावास्यमिदं सर्वं यत्किञ्च जगत्यां जगत्।','Ishavasyam idam sarvam yat kincha jagatyam jagat',
 'All this, whatever moves in this world, is pervaded by the divine.',
 'इस चराचर जगत में जो कुछ भी है, सब ईश्वर से व्याप्त है।','Isha Upanishad 1','krishna'),
(25,'मातृदेवो भव पितृदेवो भव आचार्यदेवो भव।','Matru devo bhava, pitru devo bhava, acharya devo bhava',
 'Revere your mother, father and teacher as the divine.',
 'माता को देव मानो, पिता को देव मानो, आचार्य को देव मानो।','Taittiriya Upanishad','ganesha'),
(26,'सत्यमेव जयते नानृतम्।','Satyam eva jayate nanritam',
 'Truth alone triumphs, never falsehood.',
 'सत्य की ही जय होती है, असत्य की नहीं।','Mundaka Upanishad','durga'),
(27,'अयमात्मा ब्रह्म।','Ayam atma brahma',
 'This very self is the infinite.',
 'यह आत्मा ही ब्रह्म है।','Mandukya Upanishad','shiva'),
(28,'उत्तिष्ठत जाग्रत प्राप्य वरान्निबोधत।','Uttishthata jagrata prapya varan nibodhata',
 'Arise, awake, and stop not until the goal is reached.',
 'उठो, जागो, और श्रेष्ठ पुरुषों के पास जाकर ज्ञान प्राप्त करो।','Katha Upanishad','durga'),
(29,'एकं सद्विप्रा बहुधा वदन्ति।','Ekam sad vipra bahudha vadanti',
 'Truth is one; the wise call it by many names.',
 'सत्य एक है; ज्ञानीजन उसे अनेक नामों से पुकारते हैं।','Rig Veda','shiva'),
(30,'ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि।','Om bhur bhuvah svah tat savitur varenyam bhargo devasya dhimahi',
 'We meditate on the radiant glory of the divine Sun; may it inspire our minds.',
 'हम उस सविता देव के वरणीय तेज का ध्यान करते हैं; वह हमारी बुद्धि को प्रेरित करे।','Gayatri Mantra','krishna'),
(31,'ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्।','Om tryambakam yajamahe sugandhim pushti-vardhanam',
 'We worship the three eyed one who nourishes all; may he free us from death into immortality.',
 'हम त्रिनेत्र शिव का पूजन करते हैं जो सबका पोषण करते हैं; वे हमें मृत्यु से अमरता की ओर मुक्त करें।','Mahamrityunjaya Mantra','shiva'),
(32,'ॐ पूर्णमदः पूर्णमिदं पूर्णात्पूर्णमुदच्यते।','Om purnam adah purnam idam purnat purnam udachyate',
 'That is whole, this is whole; from the whole, the whole arises.',
 'वह पूर्ण है, यह पूर्ण है; पूर्ण से ही पूर्ण उत्पन्न होता है।','Isha Upanishad','shiva'),
(33,'गुरुर्ब्रह्मा गुरुर्विष्णुर्गुरुर्देवो महेश्वरः।','Gurur brahma gurur vishnur gurur devo maheshwarah',
 'The guru is Brahma, Vishnu and Shiva; the guru is the supreme itself.',
 'गुरु ब्रह्मा हैं, गुरु विष्णु हैं, गुरु ही देव महेश्वर हैं।','Guru Stotra','ganesha'),
(34,'वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ।','Vakratunda mahakaya surya-koti samaprabha',
 'O curved trunked, mighty one, radiant as a million suns, clear my path always.',
 'हे वक्रतुण्ड, महाकाय, करोड़ों सूर्यों के समान तेजस्वी, सदा मेरे मार्ग को निर्विघ्न करो।','Ganesha Stotra','ganesha'),
(35,'या कुन्देन्दुतुषारहारधवला या शुभ्रवस्त्रावृता।','Ya kundendu tushara hara dhavala ya shubhra vastravrita',
 'O Saraswati, white as jasmine and moonlight, clad in pure white, remove my ignorance.',
 'हे सरस्वती, कुंद, चंद्र और हिम सी श्वेत, श्वेत वस्त्र धारिणी, मेरी जड़ता दूर करो।','Saraswati Stotra','ganesha'),
(36,'शान्ताकारं भुजगशयनं पद्मनाभं सुरेशम्।','Shantakaram bhujaga shayanam padmanabham suresham',
 'I bow to Vishnu, serene, resting on the serpent, the lotus naveled lord of all.',
 'मैं उन विष्णु को प्रणाम करता हूँ, जो शांत हैं, शेषनाग पर शयन करते हैं, पद्मनाभ और देवेश हैं।','Vishnu Stotra','lakshmi'),
(37,'मनोजवं मारुततुल्यवेगं जितेन्द्रियं बुद्धिमतां वरिष्ठम्।','Manojavam maruta tulya vegam jitendriyam buddhimatam varishtham',
 'Swift as thought, fast as the wind, master of the senses, wisest of the wise, I take refuge in Hanuman.',
 'मन के समान वेगवान, वायु सम गतिवान, जितेन्द्रिय, बुद्धिमानों में श्रेष्ठ, ऐसे हनुमान की मैं शरण लेता हूँ।','Hanuman Stotra','hanuman'),
(38,'या देवी सर्वभूतेषु शक्तिरूपेण संस्थिता।','Ya devi sarva-bhuteshu shakti-rupena samsthita',
 'To the Goddess who dwells in all beings as power, I bow again and again.',
 'जो देवी समस्त प्राणियों में शक्ति रूप में स्थित हैं, उन्हें बारंबार नमस्कार।','Devi Mahatmya','durga'),
(39,'सर्वमङ्गलमाङ्गल्ये शिवे सर्वार्थसाधिके।','Sarva mangala mangalye shive sarvartha sadhike',
 'O auspicious one, source of all good, fulfiller of every aim, I bow to you.',
 'हे सर्व मंगल की मंगलमयी, कल्याणी, समस्त प्रयोजनों को सिद्ध करने वाली, तुम्हें नमन।','Durga Stotra','durga'),
(40,'श्रीराम जय राम जय जय राम।','Shri Ram Jai Ram Jai Jai Ram',
 'Glory to Shri Ram, again and again.',
 'श्री राम की जय, बारंबार राम की जय।','Ram Naam','hanuman'),
(41,'उद्यमेन हि सिध्यन्ति कार्याणि न मनोरथैः।','Udyamena hi sidhyanti karyani na manorathaih',
 'Tasks are accomplished by effort, not by mere wishing.',
 'कार्य परिश्रम से सिद्ध होते हैं, केवल इच्छाओं से नहीं।','Subhashita','hanuman'),
(42,'अयं निजः परो वेति गणना लघुचेतसाम्।','Ayam nijah paro veti ganana laghu-chetasam',
 'This is mine and that a stranger, is the reckoning of the narrow minded; for the noble, the whole world is one family.',
 'यह अपना है और वह पराया, ऐसी गणना संकीर्ण मन वालों की है; उदार हृदय के लिए तो सारा संसार एक परिवार है।','Maha Upanishad','lakshmi'),
(43,'परोपकाराय फलन्ति वृक्षाः परोपकाराय वहन्ति नद्यः।','Paropakaraya phalanti vrikshah paropakaraya vahanti nadyah',
 'Trees bear fruit for others, rivers flow for others; so too a noble life is lived for others.',
 'वृक्ष दूसरों के लिए फल देते हैं, नदियाँ दूसरों के लिए बहती हैं; वैसे ही सज्जन का जीवन परोपकार के लिए है।','Subhashita','ganesha'),
(44,'सर्वे भवन्तु सुखिनः लोकाः समस्ताः सुखिनो भवन्तु।','Lokah samastah sukhino bhavantu',
 'May all the worlds, everywhere, be happy and at peace.',
 'समस्त लोकों के सभी प्राणी सुखी हों।','Shanti Mantra','krishna')
on conflict (id) do update set
  deva=excluded.deva, translit=excluded.translit, meaning=excluded.meaning,
  meaning_hi=excluded.meaning_hi, source=excluded.source, deity=excluded.deity;
