-- ============================================================================
--  DIVASYA migration 010 — Naamkaran data (all 27 nakshatras + full name bank)
--  Generated from lib/demo.ts. Bilingual: Devanagari name, Hindi deity/planet,
--  Devanagari pada syllables, and Hindi meanings on every name. Idempotent.
-- ============================================================================

insert into public.nakshatra_syllables (name,syllables,syllables_deva,deity,deity_hi,planet,planet_hi,deva,sort) values
('Ashwini','{"Chu","Che","Cho","La"}','{"चू","चे","चो","ला"}','Ashwini Kumaras','अश्विनी कुमार','Ketu','केतु','अश्विनी',1),
('Bharani','{"Li","Lu","Le","Lo"}','{"ली","लू","ले","लो"}','Yama','यम','Venus','शुक्र','भरणी',2),
('Krittika','{"A","I","U","E"}','{"अ","ई","उ","ए"}','Agni','अग्नि','Sun','सूर्य','कृत्तिका',3),
('Rohini','{"O","Va","Vi","Vu"}','{"ओ","वा","वी","वू"}','Brahma','ब्रह्मा','Moon','चंद्र','रोहिणी',4),
('Mrigashira','{"Ve","Vo","Ka","Ki"}','{"वे","वो","का","की"}','Soma','सोम','Mars','मंगल','मृगशिरा',5),
('Ardra','{"Ku","Gha","Nga","Chha"}','{"कू","घ","ङ","छ"}','Rudra','रुद्र','Rahu','राहु','आर्द्रा',6),
('Punarvasu','{"Ke","Ko","Ha","Hi"}','{"के","को","हा","ही"}','Aditi','अदिति','Jupiter','गुरु','पुनर्वसु',7),
('Pushya','{"Hu","He","Ho","Da"}','{"हू","हे","हो","डा"}','Brihaspati','बृहस्पति','Saturn','शनि','पुष्य',8),
('Ashlesha','{"Di","Du","De","Do"}','{"डी","डू","डे","डो"}','Nagas','नाग','Mercury','बुध','आश्लेषा',9),
('Magha','{"Ma","Mi","Mu","Me"}','{"मा","मी","मू","मे"}','Pitrs','पितृ','Ketu','केतु','मघा',10),
('Purva Phalguni','{"Mo","Ta","Ti","Tu"}','{"मो","टा","टी","टू"}','Bhaga','भग','Venus','शुक्र','पूर्व फाल्गुनी',11),
('Uttara Phalguni','{"Te","To","Pa","Pi"}','{"टे","टो","पा","पी"}','Aryaman','अर्यमा','Sun','सूर्य','उत्तर फाल्गुनी',12),
('Hasta','{"Pu","Sha","Na","Tha"}','{"पू","ष","ण","ठ"}','Savitr','सविता','Moon','चंद्र','हस्त',13),
('Chitra','{"Pe","Po","Ra","Ri"}','{"पे","पो","रा","री"}','Tvashtar','त्वष्टा','Mars','मंगल','चित्रा',14),
('Swati','{"Ru","Re","Ro","Ta"}','{"रू","रे","रो","ता"}','Vayu','वायु','Rahu','राहु','स्वाती',15),
('Vishakha','{"Ti","Tu","Te","To"}','{"ती","तू","ते","तो"}','Indra-Agni','इन्द्राग्नि','Jupiter','गुरु','विशाखा',16),
('Anuradha','{"Na","Ni","Nu","Ne"}','{"ना","नी","नू","ने"}','Mitra','मित्र','Saturn','शनि','अनुराधा',17),
('Jyeshtha','{"No","Ya","Yi","Yu"}','{"नो","या","यी","यू"}','Indra','इन्द्र','Mercury','बुध','ज्येष्ठा',18),
('Mula','{"Ye","Yo","Bha","Bhi"}','{"ये","यो","भा","भी"}','Nirriti','निर्ऋति','Ketu','केतु','मूल',19),
('Purva Ashadha','{"Bhu","Dha","Pha","Ddha"}','{"भू","धा","फा","ढा"}','Apas','आपः','Venus','शुक्र','पूर्वाषाढा',20),
('Uttara Ashadha','{"Bhe","Bho","Ja","Ji"}','{"भे","भो","जा","जी"}','Vishvedevas','विश्वेदेवा','Sun','सूर्य','उत्तराषाढा',21),
('Shravana','{"Ju","Je","Jo","Gha"}','{"जू","जे","जो","घा"}','Vishnu','विष्णु','Moon','चंद्र','श्रवण',22),
('Dhanishta','{"Ga","Gi","Gu","Ge"}','{"गा","गी","गू","गे"}','Vasus','वसु','Mars','मंगल','धनिष्ठा',23),
('Shatabhisha','{"Go","Sa","Si","Su"}','{"गो","सा","सी","सू"}','Varuna','वरुण','Rahu','राहु','शतभिषा',24),
('Purva Bhadrapada','{"Se","So","Da","Di"}','{"से","सो","दा","दी"}','Aja Ekapada','अज एकपाद','Jupiter','गुरु','पूर्व भाद्रपदा',25),
('Uttara Bhadrapada','{"Du","Tha","Jha","Nya"}','{"दू","थ","झ","ञ"}','Ahir Budhnya','अहिर्बुध्न्य','Saturn','शनि','उत्तर भाद्रपदा',26),
('Revati','{"De","Do","Cha","Chi"}','{"दे","दो","चा","ची"}','Pushan','पूषा','Mercury','बुध','रेवती',27)
on conflict (name) do update set
  syllables=excluded.syllables, syllables_deva=excluded.syllables_deva,
  deity=excluded.deity, deity_hi=excluded.deity_hi, planet=excluded.planet,
  planet_hi=excluded.planet_hi, deva=excluded.deva, sort=excluded.sort;

insert into public.baby_names (name,gender,meaning,meaning_hi,syllable,deva) values
('Aarav','m','Peaceful','शांत','A','आरव'),
('Aditya','m','The sun','सूर्य','A','आदित्य'),
('Arjun','m','Bright, the Pandava','तेजस्वी; एक पांडव','A','अर्जुन'),
('Amrit','m','Nectar of immortality','अमृत','A','अमृत'),
('Ananya','f','Unique','अद्वितीय','A','अनन्या'),
('Aditi','f','Boundless, mother of the devas','अनंत; देवों की माता','A','अदिति'),
('Ahana','f','First light of dawn','भोर की पहली किरण','A','अहाना'),
('Aarohi','f','Ascending melody','आरोही स्वर','A','आरोही'),
('Ishaan','m','Lord of the north-east','ईशान दिशा के स्वामी','I','ईशान'),
('Indra','m','King of the devas','देवराज','I','इन्द्र'),
('Ira','f','Earth, speech','पृथ्वी; वाणी','I','इरा'),
('Indira','f','Lakshmi','लक्ष्मी','I','इन्दिरा'),
('Ishita','f','Mastery','प्रभुत्व','I','ईशिता'),
('Udit','m','Risen','उदित','U','उदित'),
('Uday','m','Sunrise','सूर्योदय','U','उदय'),
('Utkarsh','m','Excellence','उत्कर्ष','U','उत्कर्ष'),
('Uma','f','Parvati','पार्वती','U','उमा'),
('Urvi','f','The earth','पृथ्वी','U','उर्वी'),
('Ekansh','m','A whole part','पूर्ण अंश','E','एकांश'),
('Ekagra','m','Single-pointed','एकाग्र','E','एकाग्र'),
('Ekta','f','Unity','एकता','E','एकता'),
('Esha','f','Desire','इच्छा','E','एषा'),
('Om','m','The primordial sound','आदि नाद','O','ओम्'),
('Omkar','m','The syllable Om','ॐ अक्षर','O','ओंकार'),
('Ojas','m','Vital vigour','ओज','O','ओजस'),
('Ojasvi','f','Lustrous','तेजस्वी','O','ओजस्वी'),
('Chandra','m','The moon','चंद्रमा','Cha','चन्द्र'),
('Chaitanya','m','Consciousness','चेतना','Cha','चैतन्य'),
('Charvi','f','Beautiful','सुंदर','Cha','चार्वी'),
('Chandni','f','Moonlight','चाँदनी','Cha','चाँदनी'),
('Charu','f','Graceful','लालित्यपूर्ण','Cha','चारु'),
('Chinmay','m','Full of consciousness','चैतन्यमय','Chi','चिन्मय'),
('Chirag','m','Lamp','दीपक','Chi','चिराग'),
('Chintan','m','Contemplation','चिंतन','Chi','चिन्तन'),
('Chitra','f','Picture; a nakshatra','चित्र; एक नक्षत्र','Chi','चित्रा'),
('Chinmayi','f','Full of knowledge','ज्ञानमयी','Chi','चिन्मयी'),
('Chudamani','m','Crest jewel','शिरोमणि','Chu','चूड़ामणि'),
('Chetan','m','Consciousness','चेतना','Che','चेतन'),
('Chetas','m','Mind, awareness','मन; बोध','Che','चेतस्'),
('Chetana','f','Awareness','बोध','Che','चेतना'),
('Cheshta','f','Endeavour','प्रयत्न','Che','चेष्टा'),
('Chhavi','f','Image, radiance','छवि; आभा','Chha','छवि'),
('Chhaya','f','Shade; wife of the Sun','छाया; सूर्य की पत्नी','Chha','छाया'),
('Lakshya','m','Aim, goal','लक्ष्य','La','लक्ष्य'),
('Laksh','m','Target','निशाना','La','लक्ष'),
('Lalit','m','Graceful','लालित्यपूर्ण','La','ललित'),
('Lavanya','f','Grace','लावण्य','La','लावण्य'),
('Lakshmi','f','Goddess of fortune','धन की देवी','La','लक्ष्मी'),
('Latika','f','A small vine','छोटी लता','La','लतिका'),
('Lipika','f','Script, a letter','लिपि; अक्षर','Li','लिपिका'),
('Lipi','f','Writing','लेखन','Li','लिपि'),
('Lekha','f','A written line','लिखी हुई रेखा','Le','लेखा'),
('Lohit','m','Red','लाल','Lo','लोहित'),
('Lochan','m','The eye','नेत्र','Lo','लोचन'),
('Lokesh','m','Lord of the world','लोकों के स्वामी','Lo','लोकेश'),
('Vasu','m','Wealth; one of the eight Vasus','धन; अष्ट वसुओं में एक','Va','वसु'),
('Varun','m','Lord of the waters','जल के देवता','Va','वरुण'),
('Vansh','m','Lineage','वंश','Va','वंश'),
('Vandana','f','Praise, salutation','वंदना','Va','वन्दना'),
('Vaishnavi','f','Of Vishnu','विष्णु से संबंधित','Va','वैष्णवी'),
('Varsha','f','Rain','वर्षा','Va','वर्षा'),
('Vihaan','m','Dawn','प्रभात','Vi','विहान'),
('Vivaan','m','Rays of the morning sun','प्रातःकालीन किरणें','Vi','विवान'),
('Vikram','m','Valour','पराक्रम','Vi','विक्रम'),
('Vinay','m','Modesty','विनम्रता','Vi','विनय'),
('Vidya','f','Knowledge','विद्या','Vi','विद्या'),
('Vibha','f','Radiance','तेज','Vi','विभा'),
('Ved','m','Sacred knowledge','वेद','Ve','वेद'),
('Vedant','m','End of the Vedas','वेदों का अंत','Ve','वेदान्त'),
('Vedika','f','The altar','वेदी','Ve','वेदिका'),
('Krishna','m','The dark one','श्यामवर्ण','Ka','कृष्ण'),
('Kartik','m','A month; Skanda','एक मास; कार्तिकेय','Ka','कार्तिक'),
('Kamal','m','Lotus','कमल','Ka','कमल'),
('Kavya','f','Poetry','काव्य','Ka','काव्या'),
('Kalpana','f','Imagination','कल्पना','Ka','कल्पना'),
('Kishore','m','A youth','किशोर','Ki','किशोर'),
('Kirti','f','Fame','कीर्ति','Ki','कीर्ति'),
('Kiara','f','Light','प्रकाश','Ki','कियारा'),
('Kunal','m','Lotus; son of Ashoka','कमल; अशोक का पुत्र','Ku','कुणाल'),
('Kumar','m','Young prince','राजकुमार','Ku','कुमार'),
('Kumud','m','Night lotus','कुमुदिनी','Ku','कुमुद'),
('Kusum','f','Flower','पुष्प','Ku','कुसुम'),
('Kunti','f','Mother of the Pandavas','पांडवों की माता','Ku','कुन्ती'),
('Kedar','m','A field; Shiva','क्षेत्र; शिव','Ke','केदार'),
('Keshav','m','Krishna','कृष्ण','Ke','केशव'),
('Ketan','m','Banner','ध्वज','Ke','केतन'),
('Keya','f','A monsoon flower','केतकी का पुष्प','Ke','केया'),
('Koushik','m','A sage; Vishvamitra','एक ऋषि; विश्वामित्र','Ko','कौशिक'),
('Komal','f','Tender','कोमल','Ko','कोमल'),
('Kokila','f','The cuckoo','कोयल','Ko','कोकिला'),
('Ganesh','m','Remover of obstacles','विघ्नहर्ता','Ga','गणेश'),
('Gagan','m','The sky','गगन','Ga','गगन'),
('Gauri','f','Parvati, the fair one','गौरवर्णा पार्वती','Ga','गौरी'),
('Gayatri','f','A Vedic metre and mantra','एक वैदिक छंद और मंत्र','Ga','गायत्री'),
('Girish','m','Lord of the mountain','गिरि के स्वामी','Gi','गिरीश'),
('Giri','m','Mountain','पर्वत','Gi','गिरि'),
('Gita','f','Song; the Bhagavad Gita','गीत; भगवद्गीता','Gi','गीता'),
('Guru','m','Teacher; Brihaspati','गुरु; बृहस्पति','Gu','गुरु'),
('Gunjan','f','Humming of bees','भ्रमरों का गुंजन','Gu','गुंजन'),
('Gopal','m','Cowherd; Krishna','गोपालक; कृष्ण','Go','गोपाल'),
('Govind','m','Krishna','कृष्ण','Go','गोविन्द'),
('Gopika','f','A gopi of Vrindavan','वृंदावन की गोपी','Go','गोपिका'),
('Ghanshyam','m','Dark as a raincloud; Krishna','मेघ सा श्याम; कृष्ण','Gha','घनश्याम'),
('Hari','m','Vishnu','विष्णु','Ha','हरि'),
('Harsh','m','Joy','हर्ष','Ha','हर्ष'),
('Hardik','m','Heartfelt','हृदय से','Ha','हार्दिक'),
('Hansika','f','Swan','हंसिनी','Ha','हंसिका'),
('Harshita','f','Joyful','हर्षित','Ha','हर्षिता'),
('Himanshu','m','The moon','चंद्रमा','Hi','हिमांशु'),
('Hitesh','m','Well-wisher','हितैषी','Hi','हितेश'),
('Hima','f','Snow','हिम','Hi','हिमा'),
('Hemant','m','Early winter','हेमंत ऋतु','He','हेमन्त'),
('Hemal','m','Golden','स्वर्णिम','He','हेमल'),
('Hema','f','Gold','स्वर्ण','He','हेमा'),
('Daksh','m','Able; a Prajapati','दक्ष; एक प्रजापति','Da','दक्ष'),
('Darshan','m','Sight of the divine','ईश्वर के दर्शन','Da','दर्शन'),
('Damini','f','Lightning','बिजली','Da','दामिनी'),
('Damayanti','f','The queen of Nala','नल की रानी','Da','दमयन्ती'),
('Dinesh','m','Lord of the day','दिन के स्वामी','Di','दिनेश'),
('Divit','m','Immortal','अमर','Di','दिवित'),
('Divya','f','Divine','दिव्य','Di','दिव्या'),
('Diya','f','Lamp','दीपक','Di','दीया'),
('Diksha','f','Initiation','दीक्षा','Di','दीक्षा'),
('Durgesh','m','Lord of forts','दुर्गों के स्वामी','Du','दुर्गेश'),
('Durga','f','The unassailable goddess','दुर्गम देवी','Du','दुर्गा'),
('Dulari','f','Beloved','प्रिय','Du','दुलारी'),
('Dev','m','God','देव','De','देव'),
('Devansh','m','Part of the divine','ईश्वर का अंश','De','देवांश'),
('Deepak','m','Lamp','दीपक','De','दीपक'),
('Devika','f','Little goddess','छोटी देवी','De','देविका'),
('Deepti','f','Brilliance','दीप्ति','De','दीप्ति'),
('Dhruv','m','The pole star; steadfast','ध्रुव तारा; अटल','Dha','ध्रुव'),
('Dhiraj','m','Patience','धैर्य','Dha','धीरज'),
('Dhara','f','A stream','धारा','Dha','धारा'),
('Dhanya','f','Fortunate','भाग्यशाली','Dha','धन्या'),
('Manav','m','Human','मानव','Ma','मानव'),
('Madhav','m','Krishna','कृष्ण','Ma','माधव'),
('Mayank','m','The moon','चंद्रमा','Ma','मयंक'),
('Mahi','f','The earth','पृथ्वी','Ma','मही'),
('Mansi','f','Of the mind','मन से संबंधित','Ma','मानसी'),
('Mihir','m','The sun','सूर्य','Mi','मिहिर'),
('Mitra','m','Friend; a Vedic deity','मित्र; एक वैदिक देवता','Mi','मित्र'),
('Meera','f','Devotee of Krishna','कृष्ण भक्त','Mi','मीरा'),
('Mitali','f','Friendship','मित्रता','Mi','मिताली'),
('Mukul','m','Bud, blossom','कली','Mu','मुकुल'),
('Mukund','m','Krishna, giver of liberation','मुक्तिदाता कृष्ण','Mu','मुकुन्द'),
('Mudita','f','Joy in another''s joy','दूसरों के सुख में सुख','Mu','मुदिता'),
('Muskan','f','Smile','मुस्कान','Mu','मुस्कान'),
('Mehul','m','Rain','वर्षा','Me','मेहुल'),
('Megha','f','Cloud','मेघ','Me','मेघा'),
('Medha','f','Intellect','बुद्धि','Me','मेधा'),
('Mohan','m','Enchanting; Krishna','मोहित करने वाले; कृष्ण','Mo','मोहन'),
('Mohit','m','Entranced','मुग्ध','Mo','मोहित'),
('Mohini','f','The enchantress','मोहिनी','Mo','मोहिनी'),
('Tanmay','m','Absorbed','तल्लीन','Ta','तन्मय'),
('Tanish','m','Ambition','महत्वाकांक्षा','Ta','तनिष'),
('Tanvi','f','Slender','तन्वंगी','Ta','तन्वी'),
('Tara','f','Star','तारा','Ta','तारा'),
('Tanuja','f','Daughter','पुत्री','Ta','तनुजा'),
('Tithi','f','A lunar day','तिथि','Ti','तिथि'),
('Tushar','m','Frost, snow','तुषार','Tu','तुषार'),
('Tulsi','f','Holy basil','तुलसी','Tu','तुलसी'),
('Tushti','f','Contentment','संतोष','Tu','तुष्टि'),
('Tejas','m','Radiance','तेज','Te','तेजस'),
('Tejasvi','f','Lustrous','तेजस्वी','Te','तेजस्वी'),
('Tejal','f','Radiant','तेजोमय','Te','तेजल'),
('Toshan','m','Satisfying','संतुष्ट करने वाला','To','तोषण'),
('Toshi','f','Content','संतुष्ट','To','तोषी'),
('Pranav','m','The syllable Om','ॐ अक्षर','Pa','प्रणव'),
('Parth','m','Arjuna, son of Pritha','पृथा पुत्र अर्जुन','Pa','पार्थ'),
('Pavan','m','The wind','पवन','Pa','पवन'),
('Padma','f','Lotus; Lakshmi','कमल; लक्ष्मी','Pa','पद्मा'),
('Palak','f','Eyelash','पलक','Pa','पलक'),
('Piyush','m','Nectar','पीयूष','Pi','पीयूष'),
('Pinaki','m','Shiva, bearer of the bow','पिनाकधारी शिव','Pi','पिनाकी'),
('Priya','f','Beloved','प्रिय','Pi','प्रिया'),
('Purav','m','Eastern','पूर्व दिशा का','Pu','पुरव'),
('Pushkar','m','Lotus; a sacred lake','कमल; एक पावन सरोवर','Pu','पुष्कर'),
('Punya','f','Merit','पुण्य','Pu','पुण्य'),
('Purvi','f','Eastern; a raga','पूर्वी; एक राग','Pu','पूर्वी'),
('Phalgun','m','The last lunar month','अंतिम चंद्र मास','Pha','फाल्गुन'),
('Shaurya','m','Valour','पराक्रम','Sha','शौर्य'),
('Shantanu','m','A king of Hastinapur','हस्तिनापुर के राजा','Sha','शान्तनु'),
('Shakti','f','Power','शक्ति','Sha','शक्ति'),
('Sharvani','f','Parvati','पार्वती','Sha','शर्वाणी'),
('Sarthak','m','Meaningful','सार्थक','Sa','सार्थक'),
('Samarth','m','Capable','समर्थ','Sa','समर्थ'),
('Sagar','m','Ocean','सागर','Sa','सागर'),
('Sanvi','f','Lakshmi','लक्ष्मी','Sa','सान्वी'),
('Sadhana','f','Sustained practice','साधना','Sa','साधना'),
('Siddharth','m','One who attains the goal','सिद्धि प्राप्त करने वाला','Si','सिद्धार्थ'),
('Sita','f','Consort of Rama','राम की पत्नी','Si','सीता'),
('Siddhi','f','Attainment','सिद्धि','Si','सिद्धि'),
('Simran','f','Remembrance of the divine','प्रभु स्मरण','Si','सिमरन'),
('Surya','m','The sun','सूर्य','Su','सूर्य'),
('Sujay','m','A good victory','शुभ विजय','Su','सुजय'),
('Sundar','m','Beautiful','सुंदर','Su','सुन्दर'),
('Suman','f','Flower; good-hearted','पुष्प; सुहृदय','Su','सुमन'),
('Sudha','f','Nectar','पीयूष','Su','सुधा'),
('Sena','f','Army','सेना','Se','सेना'),
('Sevak','m','One who serves','सेवक','Se','सेवक'),
('Soham','m','I am that','वही मैं हूँ','So','सोहम्'),
('Sohan','m','Handsome','मनोहर','So','सोहन'),
('Sonal','f','Golden','स्वर्णिम','So','सोनल'),
('Soumya','f','Gentle; of the moon','सौम्य; चंद्र से संबंधित','So','सौम्य'),
('Narayan','m','Vishnu','विष्णु','Na','नारायण'),
('Nakul','m','A Pandava','एक पांडव','Na','नकुल'),
('Naina','f','Eyes','नयन','Na','नैना'),
('Nandini','f','Delightful daughter','आनंद देने वाली पुत्री','Na','नन्दिनी'),
('Namrata','f','Humility','नम्रता','Na','नम्रता'),
('Nikhil','m','Complete, entire','संपूर्ण','Ni','निखिल'),
('Nishant','m','End of night, dawn','रात्रि का अंत, भोर','Ni','निशांत'),
('Nitya','f','Eternal','नित्य','Ni','नित्या'),
('Nidhi','f','Treasure','निधि','Ni','निधि'),
('Nutan','f','New','नूतन','Nu','नूतन'),
('Neel','m','Blue','नील','Ne','नील'),
('Neha','f','Love','स्नेह','Ne','नेहा'),
('Netra','f','The eye','नेत्र','Ne','नेत्र'),
('Raghav','m','Of Raghu''s line; Rama','रघुवंशी; राम','Ra','राघव'),
('Ram','m','The seventh avatar','सातवें अवतार','Ra','राम'),
('Rajat','m','Silver','रजत','Ra','रजत'),
('Radha','f','Beloved of Krishna','कृष्ण की प्रिया','Ra','राधा'),
('Rachana','f','Creation','रचना','Ra','रचना'),
('Rishabh','m','Excellent; the second note','श्रेष्ठ; दूसरा स्वर','Ri','ऋषभ'),
('Riya','f','Singer','गायिका','Ri','रिया'),
('Ridhi','f','Prosperity','समृद्धि','Ri','ऋद्धि'),
('Ritu','f','Season','ऋतु','Ri','ऋतु'),
('Rudra','m','A form of Shiva','शिव का एक रूप','Ru','रुद्र'),
('Ruchi','f','Taste, interest','रुचि','Ru','रुचि'),
('Rupa','f','Form, beauty','रूप; सौंदर्य','Ru','रूपा'),
('Reyansh','m','A ray of light','प्रकाश की किरण','Re','रेयांश'),
('Reva','f','The Narmada','नर्मदा नदी','Re','रेवा'),
('Renu','f','Pollen, fine dust','पराग; सूक्ष्म रज','Re','रेणु'),
('Rohan','m','Ascending','आरोहण करने वाला','Ro','रोहन'),
('Rohit','m','Red','लाल','Ro','रोहित'),
('Roshni','f','Light','प्रकाश','Ro','रोशनी'),
('Yash','m','Glory','यश','Ya','यश'),
('Yajna','m','Sacrifice, offering','यज्ञ','Ya','यज्ञ'),
('Yashoda','f','Krishna''s foster mother','कृष्ण की माता यशोदा','Ya','यशोदा'),
('Yamini','f','Night','रात्रि','Ya','यामिनी'),
('Yug','m','An age of the world','एक युग','Yu','युग'),
('Yuvraj','m','Crown prince','युवराज','Yu','युवराज'),
('Yukti','f','Reason, stratagem','युक्ति','Yu','युक्ति'),
('Yogesh','m','Lord of yoga','योग के स्वामी','Yo','योगेश'),
('Yogi','m','One joined in yoga','योगी','Yo','योगी'),
('Yogita','f','Absorbed in yoga','योग में लीन','Yo','योगिता'),
('Bharat','m','A king; India','एक राजा; भारत','Bha','भरत'),
('Bhavesh','m','Lord of feeling','भावों के स्वामी','Bha','भावेश'),
('Bhavya','f','Grand, splendid','भव्य','Bha','भव्या'),
('Bhakti','f','Devotion','भक्ति','Bha','भक्ति'),
('Bhima','m','Mighty; a Pandava','बलशाली; एक पांडव','Bhi','भीम'),
('Bhuvan','m','World','भुवन','Bhu','भुवन'),
('Bhushan','m','Ornament','आभूषण','Bhu','भूषण'),
('Bhumi','f','The earth','पृथ्वी','Bhu','भूमि'),
('Jagat','m','The world','जगत','Ja','जगत्'),
('Jatin','m','An ascetic','तपस्वी','Ja','जतिन'),
('Jaya','f','Victory','विजय','Ja','जया'),
('Janhvi','f','The Ganga','गंगा','Ja','जान्हवी'),
('Jitendra','m','Conqueror of the senses','इंद्रियों को जीतने वाला','Ji','जितेन्द्र'),
('Jiya','f','Heart','हृदय','Ji','जिया'),
('Jivika','f','Livelihood','जीविका','Ji','जीविका'),
('Juhi','f','A jasmine','जूही का पुष्प','Ju','जूही'),
('Jeet','m','Victory','विजय','Je','जीत'),
('Jyoti','f','Light, flame','ज्योति','Jo','ज्योति'),
('Jyotsna','f','Moonlight','चाँदनी','Jo','ज्योत्स्ना')
on conflict (name) do update set
  gender=excluded.gender, meaning=excluded.meaning, meaning_hi=excluded.meaning_hi,
  syllable=excluded.syllable, deva=excluded.deva;
